### ISSUE TITLE
CRUD API of the endpoints for the Area entity

### ISSUE THREAD

**Issue by kuzinmv** [kuzinmv/aveproject#12]
Create a basic application data layer.
Based on the CRUD API of the endpoints for the Area entity.
Please use screenshots to understand the user experience and button layout.

![Image](https://user-images.githubusercontent.com/6621928/236990764-730ce8db-19e1-4dfd-90f8-770b2a6c9f69.jpeg)
![Image](https://user-images.githubusercontent.com/6621928/236990766-0bd2f2db-3a5e-4678-91f7-cac382e2e7a5.jpeg)
![Image](https://user-images.githubusercontent.com/6621928/236990765-1fc2437f-787f-423f-a7a2-249c11d47b84.jpeg)
![Image](https://user-images.githubusercontent.com/6621928/236990767-474c0954-6cd5-478d-8697-b7bf5308b42d.jpeg)

http://localhost:3000/api#/Area

**Comment by dron888** [comment]
Done
