### ISSUE TITLE
Create a sample application

### ISSUE THREAD

**Issue by kuzinmv** [kuzinmv/aveproject#7]
Create a sample application, use one of the examples for OL to draw objects.

https://openlayers.org/en/latest/examples
https://openlayers.org/en/latest/examples/snap.html
https://openlayers.org/en/latest/examples/vector-esri-edit.html

Map component
Upper application control panel (buttons, menus)
Left panel for everything
In the left panel, for example, make a couple of buttons for 
- Appearance of a modal window
- Succes/Error alert

**Comment by dron888** [comment]
Done
